services:
  customer-service:
    build: .
    hostname: customerservicehost
    ports:
      - "7000:8081"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      mysql1:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7001/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 150s


  mysql1:
    image: 'mysql:latest'
    environment:
      - "MYSQL_DATABASE=customers-db"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=pwd"
      - "MYSQL_ROOT_PASSWORD=verysecretpwd"
    ports:
      - "3307:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-uuser",
          "-ppwd",
          "-h",
          "localhost"
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin1:
    image: phpmyadmin:5.2.0
    container_name: PhpMyAdmin1
    links:
      - mysql1
    restart: always
    ports:
      - 5013:80
    environment:
      - PMA_ARBITRARY=1