# src/main/resources/application.yml

# ────────────────────────────────────────────────────────────────────────────────
# Default Spring Profile & Common Settings
# ────────────────────────────────────────────────────────────────────────────────

# Default server error configuration
server:
  error:
    include-message: always

# Logging levels
logging:
  level:
    root: INFO
    com.haikel: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Hibernate will always attempt SQL init on startup
sql:
  init:
    platform: mysql
    mode: always

spring:
  # ────────────────────────────────────────────────────────────────────────────────
  # Common Hikari settings
  # ────────────────────────────────────────────────────────────────────────────────
  datasource:
    hikari:
      initializationFailTimeout: 60000

---
# ────────────────────────────────────────────────────────────────────────────────
# Override for “docker” profile
# ────────────────────────────────────────────────────────────────────────────────
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    # point at the Docker service name
    url: jdbc:mysql://mysql_server4:3306/milestone1?useSSL=false&serverTimezone=UTC
    username: user
    password: secretpwd

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# expose your application on port 8080 when running
server:
  port: 8080
