server:
  error:
    include-message: always
  port: 8084

spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:mysql://mysql_server4:3306/product-db
    username: user
    password: secretpwd

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      platform: mysql
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.example: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
