version: "3.8"

services:

  mongo:
    image: mongo:6
    container_name: order-service-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=orderdb
    healthcheck:
      test: [ "CMD-SHELL", "mongo --quiet --eval 'db.adminCommand({ping:1})'" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s



  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-service
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "7001:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/orderdb
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s


